### ISSUE TITLE
SvnInfo returns last revision number of whole repository, not a requested subfolder

### ISSUE THREAD

**Issue by Serjis** [martoe/gradle-svntools-plugin#11]
For example, I've got repository:
* / (last rev = 100)
  * project1 (last rev = 100)
    * trunk (last rev = 100)
    * branches (last rev = 90)
  * project2 (last rev = 50)
    * trunk (last rev = 40)
    * branches (last rev = 50)

and build.gradle as:

    task checkout(type: at.bxm.gradleplugins.svntools.SvnCheckout) {
        svnUrl = "https://svnserver/project2/trunk"
        workspaceDir = "src"
    }
    task vcsInfo(type: at.bxm.gradleplugins.svntools.SvnInfo) {
        sourcePath = "src"
        doLast {
            println "vcsInfo: lastRev = ${project.svnData.revisionNumber}"
        }
    }

When I call 

'gradle checkout vcsInfo'

, I get output 
'vcsInfo: lastRev = 100'

But I expect to get lastRev = 40.
How can I get 40 as last revision number? Thanks in advance.

**Comment by martoe** [comment]
Thanks @Serjis for reporting!
I committed a fix - could you check if this works out before I do a release?

**Comment by Serjis** [comment]
Hi, Martin,

I can't recompile the plugin locally. I've downloaded the project from
https://github.com/martoe/gradle-svntools-plugin/tree/fbb942d141d69b321c0dbfe635dafbc932b9a423,
and any 'gradle ...' running answers:

"Error resolving plugin [id: 'nu.studer.plugindev', version: '1.0.3']
> The response from
https://plugins.gradle.org/api/gradle/2.4/plugin/use/nu.studer.plugindev/1.0.3
was not a valid response from a Gradle Plugin Resolution Service: conte
nt type is 'text/html', expected 'application/json'"

(I've even added  buildscript { dependencies { classpath
'nu.studer:gradle-plugindev-plugin:1.0.3' } } in a gradle.build, but it
brought no result).

How can I check your fix? Could you send me a ready
gradle-svntools-plugin-xxx.jar with this fix?

Thanks!


С уважением,
Сергей Стрижков.

2015-05-27 22:28 GMT+03:00 Martin E. <notifications@github.com>:

**Comment by martoe** [comment]
Guess it is either a network issue (do you use a proxy server?) or a Gradle incompatibility (try using "gradlew"). 
I uploaded the SNAPSHOT jar to https://ocl.bxm.at/index.php/s/YiRNP1YUqf26kDq

Cheers,
Martin

**Comment by Serjis** [comment]
Perfect! This version works correctly, so I'm waiting for a release. Thank
you for your operativeness!

And you're right - it's because our damn proxy.

С уважением,
Сергей Стрижков.

2015-05-28 10:21 GMT+03:00 Martin E. <notifications@github.com>:

**Comment by martoe** [comment]
v1.1.1 released

**Comment by Serjis** [comment]
Hi,

I inform that v1.1.1 works correctly, as well as a morning snapshot. Thanks
again!

С уважением,
Сергей Стрижков.

2015-05-28 11:29 GMT+03:00 Martin E. <notifications@github.com>:
