### ISSUE TITLE
Checkout a immediate children from repository (not a whole repository)

### ISSUE THREAD

**Issue by Serjis** [martoe/gradle-svntools-plugin#12]
For example, I've got repository:
* repos/
  * project1
    * trunk
    * branches
      * branch1
      * branch2
  * project2
    * trunk
    * branches

and I need to checkout project1/branches/branch2 (or even project1/branches/branch2/somefile.txt).

If build.gradle looks like:

    task checkout(type: at.bxm.gradleplugins.svntools.SvnCheckout) {
        svnUrl = "https://svnserver/repos/project1/branches/branch2"
        workspaceDir = "workspace"
    }

, I get a folder structure as:
* /workspace
  * /.svn
  * /branch2

How can I get the following structure (without downloading the rest of the repository)?
* /workspace
  * /.svn
  * /project1
    * /branches
      * /branch2

Thanks in advance.

**Comment by martoe** [comment]
While this is supported by SVN (e.g. http://stackoverflow.com/a/50980), it is currently not possible with this plugin.

The first idea to implement this is to introduce a new `depth` attribute to the `SvnCheckout` task  and to write a new `SvnUpdate` task. These tasks could then be chained together like desribed on the mentinoned SO page.

**Comment by martoe** [comment]
Currently not needed. Feel free to reopen ;-)
