### ISSUE TITLE
Support the proxy configuration of Gradle

### ISSUE THREAD

**Issue by lwolter** [martoe/gradle-svntools-plugin#14]
To access subversion server I must use a proxy server. 

I have the proxy server defined in ~ /.gradle/gradle.properties and in ~ /.subersion/servers. Unfortunately, without success. What can I do.

**Comment by martoe** [comment]
Hi,

the ~/subversion/servers file should be the right place for your proxy config (see e.g. http://svnkit.com/kb/user-guide-config-settings.html). Unfortunately I have no proxy server at hand to check this. Can you provide an error message or stacktrace?

Cheers,
Martin

**Comment by martoe** [comment]
@lwolter I finally found a proxy to test against - implemented in plugin version 1.2, see https://github.com/martoe/gradle-svntools-plugin/blob/master/docs/GeneralConfig.md
