### ISSUE TITLE
about 'SvnTag task ' 

### ISSUE THREAD

**Issue by jerryting** [martoe/gradle-svntools-plugin#15]
I found that the task 'svntag' will (only) tag a revision to svn tags root directory, if i want to a tags/folder.
what should i do?  
please help me! thank U

**Comment by martoe** [comment]
Can you give me an example? (how does your repo structure look like; which directory do you want to be tagged; what URL should the new tag have)

**Comment by jerryting** [comment]
version = "1.0-SNAPSHOT"
task svnTag(type: at.bxm.gradleplugins.svntools.tasks.SvnTag) {
  username = 'builder'
  password = 'builder'
  tagName = "v$project.version"
  commitMessage = "Release version $project.version"
}

task releaseN(dependsOn: svnTag){
}

that is my build script likes ur sample;

my svn repos tree:
     trunk:
     tags:
           tags/mytags
     branches:

I want to do that svnTag task to tag to tags/mytags directory , how to configure it
thank u

**Comment by martoe** [comment]
In that case, the "tagName" should be `mytags/v$project.version`...
...**but**: currently slashes are not allowed within tag names, so a small patch is needed. I can create that patch later today if this is ok for you

**Comment by jerryting** [comment]
my config: tagName = "mytags/v$project.version"
It does not work

error msg : " tagName contains invalid chars: mytags/v1.0-SNAPSHOT "

i will wait ur newest release, thank u and thanks ur good job

**Comment by martoe** [comment]
v1.2.1 released - can you give it a try?

**Comment by jerryting** [comment]
After a test ，It works .so great , thanks very much.
so beautiful..
mybe, I can try to learn Groovy....O(∩_∩)O
