### ISSUE TITLE
svnversion support

### ISSUE THREAD

**Issue by GregDThomas** [martoe/gradle-svntools-plugin#20]
The svnversion command is a useful tool that displays the status of the local working copy, e.g. 

16036:16038M

It would be useful to get that information from the plugin, too.

**Comment by martoe** [comment]
How would you use the output of the `svnversion` command in your build process? (Just dumping the result to stdout doesn't make much sense to me)
Can you provide a sample usecase?

**Comment by GregDThomas** [comment]
Sorry, I should have explained myself better; what I was after was the the information currently output by `svnversion`

We currently have two use cases where we use this output;

a) Our Manifest.mf is generated by something like;

    manifest {
        attributes("SVN-URL": svntools.info.url)
        attributes("SVN-Revision": getSvnRevision())
    }

Where `getSvnRevision()` is, e.g. `16036:16038M`. This can contain more than just the existing `info.revisionNumber` as it shows mix-revision, modified, switched and partial wc's. 

b) For formal (i.e. non-SNAPSHOT) releases, the build will fail if we have mixed-revision or modified wc (i.e. the svnversion contains `:` or  doesn't end with a digit).

As far as I can tell, this isn't available from the plugin (we're currently running exec() and grabbing stdout).

**Comment by martoe** [comment]
Hi @GregDThomas,
I had a deeper look into this. My idea is to implement a "SvnVersion" task that works just like the "SvnInfo" task, only providing some different data:
* the minimum revision
* the maximum revision
* a "modified" flag
* a "switched" flag

so you can write code like this:
```
task myversion << {
  println "svnversion is $svntools.version"
  println "minimum revision is $svntools.version.minRevision"
  println svntools.version.modified ? "workspace is dirty" : "workspace is clean"
}
```
which would output something like:
```
svnversion is 4212:4168MS
minimum revision is 4168
workspace is dirty
```
Does this fit for you?
Btw: how would `svnversion` contain info about partial WCs? http://svn.gnu.org.ua/svnbook/svn.ref.svnversion.re.html doesn't say anything about this...

**Comment by GregDThomas** [comment]
I think that must be a link to an older version; http://svnbook.red-bean.com/en/1.7/svn.ref.svnversion.re.html matches the output from `svnversion --help` 

> svnversion will also inform you if the target working copy is sparsely populated (see the section called “Sparse Directories”) by attaching the 'P' code to its output

**Comment by GregDThomas** [comment]
Also, as a thought, is it necessary to have it as an explicit task? Could the additional information you're exposing (i.e. minRevision/maxRevision/isModified/isSwitched/isSparse) simply be attributes of the existing svntools.info object and the SvnInfo task - as essentially it's extra information about the wc which these already reference.

**Comment by martoe** [comment]
1. sorry for the wrong link - but even the correct one doesn't say anything about "partial wcs"...
1. do you actually need that "sparse" feature? (just asking because it would need some extra effort)
1. no, it is not necessary to have an explicit task. But I think it is better to use a new object ("svntools.version") instead of the existing "svntools.info": this new object will be populated on demand, saving time for the majority of users that don't need this information...

**Comment by GregDThomas** [comment]
A1. Sorry, I was treating sparse & partial as the same thing. Sparse is the correct terminology, my bad.
A2. No, I don't need it, was just suggesting it to get feature-parity with the `svnversion` command.
A3. Fair enough, I was unsure as to the level of overhead involved.

**Comment by martoe** [comment]
I have finished the implementation in the "develop" branch - can you try it out before I release a new version?

**Comment by GregDThomas** [comment]
Any clues on usage? I had a go with the following, based on your earlier comment, and it's not recognising "version", so I'm missing something ...

    task myversion(type: at.bxm.gradleplugins.svntools.tasks.SvnVersion) {
        println "svnversion = $svntools.version"
        println "minRevisionNumber = $svntools.version.minRevisionNumber"
        println "maxRevisionNumber = $svntools.version.maxRevisionNumber"
        println "Modified? $svntools.version.modified"
        println "Switched? $svntools.version.switched"
    }

**Comment by martoe** [comment]
Sorry, forgot to push yesterday night.
Sample buildscript, showing the two flavours:
```
buildscript {
  repositories {
    mavenLocal()
    jcenter()
  }
  dependencies {
    classpath("at.bxm.gradleplugins:gradle-svntools-plugin:1.4-SNAPSHOT")
  }
} 
apply plugin: "at.bxm.svntools"

task tryout << {
  println "svnversion: $svntools.version"
  println "modified: $svntools.version.modified"
}

task tryout2(type: at.bxm.gradleplugins.svntools.tasks.SvnVersion) << {
  println "svnversion: $svnVersion"
  println "modified: $svnVersion.modified"
}
```

**Comment by GregDThomas** [comment]
The `tryout2` flavour seems fine; thanks. 
The `tryout` flavout is complaining 

> Could not find property 'version' on at.bxm.gradleplugins.svntools.SvnToolsPluginExtension_Decorated@386978c4.

but perhaps I missing something?

**Comment by martoe** [comment]
Make sure that you have pulled the last chenges - I pushed this just 30 minutes ago. After building the plugin, run the script with the `--refresh-dependencies` switch

**Comment by GregDThomas** [comment]
Aha, `--refresh-dependencies` has got it! It all seems to be working well, many thanks!
