### ISSUE TITLE
Feature request: SvnInfo method that can be used during configuration

### ISSUE THREAD

**Issue by wenslayer** [martoe/gradle-svntools-plugin#21]
I find myself in a situation where I need to run SvnInfo against a path outside of the project hierarchy as part of the configuration phase (I do appreciate the prepopulated `svntools.info` property for the project itself that can be used during configuration). Is it even possible? If not, any suggestions for workarounds (e.g.: call 'svn info' directly)?

If SvnInfo (and other tasks) could be called like a method, in addition to a task, that would be very helpful to perform SVN actions during the configuration phase.

**Comment by martoe** [comment]
This code should work out of the box:
```
apply plugin: "at.bxm.svntools"

svntools {
  username = "john"
  password = "secret"
}

println "SvnInfo at config time: " + svnInfo(".")

def svnInfo(String path) {
  return at.bxm.gradleplugins.svntools.internal.SvnSupport.createSvnData(
    file(path), project.svntools.username, project.svntools.password,
    project.svntools.proxy, false)
}
```
Of couse this is bad code since it uses an internal API.
I would suggest to add a `createInfo(File)` method to the `svntools` extension, which would make the following work:
```
apply plugin: "at.bxm.svntools"

svntools {
  username = "john"
  password = "secret"
}

println "SvnInfo at config time: " + svntools.createInfo(file("."))
```
What do you think?

**Comment by wenslayer** [comment]
Thanks @martoe, the workaround meets my immediate need. It would be nice if the plugin exposed a method as you describe.

**Comment by martoe** [comment]
[v1.5](https://github.com/martoe/gradle-svntools-plugin/releases/tag/v1.5) released
