### ISSUE TITLE
SvnVersion incorrectly detects externals as modified

### ISSUE THREAD

**Issue by GregDThomas** [martoe/gradle-svntools-plugin#23]
If you have an unmodified svn:externals in your project then the SvnVersion incorrectly thinks that your WC is modified. Taking the following as an example;
* `common-utils` is a svn:external directory
* At the command line, `svnversion` correctly identifies that the WC is not modified
* At the command line, `svn status` correctly identifies that the WC is not modified (and nor is common-utils),
**but**
* The `svntools.version` thinks that the WC **_is_** modified
* The `svntools.version.modified` thinks that the WC **_is_** modified

```
C:\Greg\test>type test.gradle
buildscript {
  repositories {
    mavenLocal()
    jcenter()
  }
  dependencies {
    classpath("at.bxm.gradleplugins:gradle-svntools-plugin:latest.integration")
  }
}
apply plugin: "at.bxm.svntools"

task example1(description: "Using the implicit 'svntools.version' object") << {
  println "'svnversion' output: $svntools.version"
  println svntools.version.modified ? "working copy is dirty" : "working copy is clean"
}

C:\Greg\test>svnversion
16635

C:\Greg\test>svn status
X       common-utils

Performing status on external item at 'common-utils':

C:\Greg\test>gradle -b test.gradle example1
:example1
'svnversion' output: 16635M
working copy is dirty

BUILD SUCCESSFUL

Total time: 7.609 secs
C:\Greg\test>
```

**Comment by martoe** [comment]
@GregDThomas thanks for reporting. I pushed a fix to the develop branch - can you check if it works for you?

**Comment by martoe** [comment]
[v1.5](https://github.com/martoe/gradle-svntools-plugin/releases/tag/v1.5) released

**Comment by GregDThomas** [comment]
Apologies, not had to time to look at this, but thanks for fixing, it's working great :)
