### ISSUE TITLE
svn info with url, svn co depth option

### ISSUE THREAD

**Issue by MS-Astra** [martoe/gradle-svntools-plugin#26]
hi,

I'd like to have the option to check if a repository **url** exists or not.

Actually I can try to checkout an url, but this results in an exception if the url doesn't exists. So to avoid this, my idea was to check the url at first with svnInfo.

Additional it would be fine to have the **depth** option for svnCheckout to easily import e.g. a non existent folder in a very large repo (without a complete checkout)

**Comment by martoe** [comment]
@MS-Astra can you please split this into two separate issues?

**Comment by martoe** [comment]
@MS-Astra I have implemented the repo-URL-check in the `develop` branch - check out the example at https://github.com/martoe/gradle-svntools-plugin/blob/develop/docs/GeneralConfig.md

**Comment by MS-Astra** [comment]
@martoe thxs, it works fine.
