### ISSUE TITLE
Repo credentials need to be encrypted

### ISSUE THREAD

**Issue by simon0117** [martoe/gradle-svntools-plugin#28]
The svn repository credentials in username and password should be encrypted, or at least be able to be moved to a private file like ~/gradle.settings

**Comment by martoe** [comment]
Using `~/gradle.properties` for credentials is the easiest way, and supported by core Gradle, I added a note to the [documentation](https://github.com/martoe/gradle-svntools-plugin/blob/master/docs/GeneralConfig.md#svn-credentials)
For real encryption, I suggest using an additional plugin, e.g. [maven-settings-plugin](https://github.com/mark-vieira/gradle-maven-settings-plugin) or [credentials-plugin](https://github.com/etiennestuder/gradle-credentials-plugin)
