### ISSUE TITLE
Plugin incompatible with Gradle 3

### ISSUE THREAD

**Issue by dkaminsky** [martoe/gradle-svntools-plugin#34]
The move of the DynamicObject class from from  org.gradle.api.internal to org.gradle.api.internal.metaobject in Gradle 3 release breaks plugin.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':plugins:release-gradle-plugin:compileGroovy'.
> Unable to load class at.bxm.gradleplugins.svntools.internal.SvnBaseTask due to missing dependency org/gradle/api/internal/DynamicObject

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Since the MO in gradle is to always use latest and greatest (via wrapper), would it make sense to jump up to base on Gradle 3 as of a certain release #? Or do a separate release versioning scheme? 

See: https://discuss.gradle.org/t/missing-dependency-org-gradle-api-internal-dynamicobject-prevents-extending-plugin-task/19472

**Comment by martoe** [comment]
Thx for reporting. I will update the plugin to Gradle 3.

...but: I cannot reproduce this error. Can you please post your build.gradle ?

**Comment by dkaminsky** [comment]
Unfortunately no due to constraints of my employment. I don't think we are doing anything especially strange -- the context is a gradle plugin that relies on and extends your plugin to use it internally to release code from an SVN repo to a staging environment - we expose tasks to check if there are local modifications, verify you are running from a branch or tag, and have some tasks that commit updated release metadata to the SVN repo. As a result IIRC we have tasks of type SvnInfo, SvnCopy, SvnCommit (sorry not in front of computer atm so this is from memory)

**Comment by martoe** [comment]
Ok, I can reproduce it when extending the plugin with a `buildSrc` folder. The "gradle3" branch fixes this, I will release a new plugin version within the next days

**Comment by martoe** [comment]
v2.0 released
