### ISSUE TITLE
Tagging with spaces

### ISSUE THREAD

**Issue by GregDThomas** [martoe/gradle-svntools-plugin#35]
I can't seem to tag use SvnTag with a tagFolder that contains spaces / URL encoding of spaces ...

    :tag FAILED
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':tag'.
    > tagName contains invalid chars: test-tag/dir with spaces/tag-id

And if I attempt to encode those spaces ...

    :tag FAILED
  
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':tag'.
    > tagName contains invalid chars: test-tag/dir%20with%20spaces/tag-id

It looks to me like `at.bxm.gradleplugins.svntools.internal.SvnCopy.isValidName(String)` is too over-eager in it's validation. It may be simpler to simply use https://docs.oracle.com/javase/7/docs/api/java/net/URI.html#URI(java.lang.String) and use the URISyntaxException to spot if it's invalid.

**Comment by martoe** [comment]
I agree that this validation is too strict (it served my purpose at that time).
After some research I think the best idea is to allow any ASCII char, and just exclude certain chars that can cause trouble:
*  `:`
* `/`
* `\`
* `@`
* whitespaces at beginning or end
* whitespaces other than blanks (i.e. tabs, CRs etc)

Would that be fine with you?

**Comment by GregDThomas** [comment]
That would certainly solve my immediate problem (*). 

However, I still think creating a URI is perhaps a better mechanism. If there is a URISyntaxException then it's definitely wrong. A SVN URL should not have any query params (`getQuery() == null`) or a fragment (`getFragment() == null`). A whitespace is invalid (though browsers often accept it, svn might too) so should be encoded to %20. And there's nothing wrong with encoded whitespace at the beginning or end.

(*) Well, I worked around it for now with a rather nasty .replaceAll("%20", "-space-") !

**Comment by martoe** [comment]
I'm not sure about URI encoding. In my tests, I ended up with a "%20" in the branch name. Looks like the URL handling varies between different SVN servers (and/or operating systems)...

Another suggestion:
We could leave the `SvnCopy.isValidName` method as-is (as a very defensive approach) and introduce a new task config value (e.g. "allowSpecialChars=true") which just skips the name validation (for those who know excatly what they are doing)

**Comment by GregDThomas** [comment]
Yes, that sounds like it should work!
