### ISSUE TITLE
SvnCommit without PathValidation.EXISTS check

### ISSUE THREAD

**Issue by paulk-asert** [martoe/gradle-svntools-plugin#36]
I have used SvnDelete to delete a directory of files no longer needed and they have been successfully removed from the file system and scheduled for deletion with svn. Then I tried to commit the deletion but the SvnCommit task is checking that the file exists and even trying to re-add it. I think it would be better if SvnCommit didn't try to be quite as smart. Perhaps some flags could be used? autoCheck and/or autoAdd? I'd default them to false but I guess that is your call.

**Comment by martoe** [comment]
You are right, I didn't thought of that when adding the SvnDelete task.
So the desired behaviour obviously is:
* if a file/directory is scheduled for deletion, don't check its existence; and of course don't re-add it.

I will fix this

**Comment by martoe** [comment]
v2.1.1 released
