### ISSUE TITLE
SvnCommit with depth or recursive option?

### ISSUE THREAD

**Issue by paulk-asert** [martoe/gradle-svntools-plugin#37]
I have done an SvnAdd on a directory with the recursive flag set to true. This correctly schedules all of the nested files within subdirectories for addition. To commit I then need to explicitly list all files since the depth is set to EMPTY. It might be nice to also allow a recursive flag on SvnCommit or otherwise allow the SvnDepth to be altered. I guess there are a number of ways that such a feature could be made to work but I'd suggest a recursive property which if set to true caused the depth to be infinity and did a check that source was of size one.

**Comment by martoe** [comment]
I will add the "recursive" flag to the SvnCommit task

**Comment by martoe** [comment]
v2.1.1 released

**Comment by paulk-asert** [comment]
Looks good - at first I was worried what might happen if you had files and set recursive to true but I guess INFINITY depth on a file is probably like a no-op, so I think it's okay. But I'll let you know if I spot any issues.
