### ISSUE TITLE
New Feature Request: SVN CleanUp

### ISSUE THREAD

**Issue by charro** [martoe/gradle-svntools-plugin#40]
Hi ! 

Do you think it could be possible to have a CleanUp task ? It would be very useful to fix "locked" local repo problems.

Cheers and great job already here, by the way!
Miguel

**Comment by martoe** [comment]
I'm thinking of a very simple task with just one parameter (the path to be cleaned up). Would this be sufficient for you?

Martin

**Comment by charro** [comment]
Hey Martin !

Sorry for the late answer. Yes, that sounds great to me. Nothing but the path should be needed.
I guess it cleans recursively all children by default right ?
Regards

Miguel

**Comment by martoe** [comment]
Yes, cleanup is recursively. I will release a new plugin version later today

**Comment by charro** [comment]
Hi !
It looks my gradle can't find the new cleanup Task. I'm pointing to

at.bxm.gradleplugins:gradle-svntools-plugin:latest.release

Any idea ?

**Comment by martoe** [comment]
Try replacing "latest.release" with the real version number ("2.2"). If it still doesn't work, please post your build.gradle file and the error message
