### ISSUE TITLE
SVN Gradle checkout failed and says Authentication Required for SVN access.

### ISSUE THREAD

**Issue by vaibhav259** [martoe/gradle-svntools-plugin#43]
Hi Martoe, I am facing an issue with SVN-Gradle checkout. The error says svn: E170001 -Authentication Required for SVN access. I have enough permissions for that SVN repo and I work on it daily.

FYR, I have attached both build.gradle and Gradle.prop's, I'm using. Let me know where I went wrong. Thanks,
Vaibhav.
 
![gradle properties](https://user-images.githubusercontent.com/22019603/30669324-90774b20-9e23-11e7-89b2-59a541d18501.jpg)
![build gradle](https://user-images.githubusercontent.com/22019603/30669323-907743e6-9e23-11e7-8037-610292145b1c.jpg)

**Comment by martoe** [comment]
Lines 27 and 28 are wrong. delete these two lines, because you already provide these credentials in lines 23 and 24.
Btw: "svntools.username" is just a string, not a reference to a variable. Maybe you wanted to write "$svntools.username"...

Cheers,
Martin

**Comment by martoe** [comment]
No response from @vaibhav259 - assuming it is fixed...
