### ISSUE TITLE
I don‘t understand some parameter for？

### ISSUE THREAD

**Issue by WayenZ** [martoe/gradle-svntools-plugin#44]
In the Class "SvnVersionData", there are tow parameter "minRevisionNumber" &"maxRevisionNumber" ,what is each representative?

**Comment by GregDThomas** [comment]
Each file in a working copy can be at a different revision (a mixed revision working copy). The min/max represents the range in revision numbers.

**Comment by WayenZ** [comment]
"minRevisionNumber" is the svn version code that i checkout first time ,Can I think so?

**Comment by GregDThomas** [comment]
There's a better explanation that I can give at https://stackoverflow.com/questions/4232175/subversion-mixed-revisions

**Comment by martoe** [comment]
As @GregDThomas already pointed out, it is all about "mixed revisions". You may want to read the [SVN manual](http://svnbook.red-bean.com/en/1.7/svn.basic.in-action.html#svn.basic.in-action.mixedrevs) if that concept is new to you.
"minRevisionNumber" is the revision of the "oldest" file/directory within the current working copy, "maxRevisionNumber" is the revision of the "newest" one.

**Comment by WayenZ** [comment]
@GregDThomas @martoe  thanks ,it truly help me.
