### ISSUE TITLE
'E170001: Authentication required'

### ISSUE THREAD

**Issue by ghost** [martoe/gradle-svntools-plugin#51]
i run the following command: >> ./gradlew checkoutSvntools

Here is fragment from build.gradle:

apply plugin: “at.bxm.svntools”

task checkoutSvntools(type: SvnCheckout) {
svnUrl = “svn+ssh://svn.marklogic.com/project/engsvn/qa/branches/b10_0/lib”
workspaceDir = “$buildDir”
}

I don’t have any errros if I run: >> svn co svn+ssh://svn.marklogic.com/project/engsvn/qa/branches/b10_0/lib

How I can tell gradle to take existing environemnt ssl credentials?

**Comment by martoe** [comment]
This is not possible. It is a design goal of the plugin to ignore the environment and use only the configuration provided by Gradle
