### ISSUE TITLE
Use of $svntools.info in conjunction with SvnInfo task's sourcePath property

### ISSUE THREAD

**Issue by neiljbrown** [martoe/gradle-svntools-plugin#7]
Hi Martin, 

When using the SvnInfo task's sourcePath property, I've found that the task only supports accessing the svn info via $project.svnData and not $svntools.info. Attempts to access $svntools.info from within the task (e..g using a doLast {} action) fail with the error:  
"Could not execute svn-info on <$project.projectDir> (svn: E155007: ‘<$project.projectDir>' is not a working copy)"

Should $svntools.info respect the sourcePath? Does the project documentation need clarifying to state when $svntools.info and $project.svnData can and can't be used?

Thanks.

**Comment by martoe** [comment]
"$svntools.info" was meant to be a shortcut for getting infomation about the current workspace, and therefore doesn't have all the configuration options of the "SvnInfo" task. Guess it makes sense to change that - let me think about it

**Comment by neiljbrown** [comment]
I've given this issue some further thought and realized that was in part caused by my misunderstanding of how SvnInfo sourcePath property is intended to be used, and also the particular scenario I was testing.

I now realize / assume that the sourcePath property and the SvnData object is intended to support retrieving SVN info on specific files within the SVN workspace, whereas $svntools.info always contains the SVN info for the root folder of the workspace, which is always assumed to be in the root directory of the project.

I was testing the scenario where the SVN workspace was only checked-out in a sub-folder of the project, and there was no workspace in the project root directory. And I was using the sourcePath property to point to the workspace in the sub-folder. If my assumption that $svntools.info always refers to the project root folder is correct, then this would explain why I got the SVN "...is not a working copy" error.

The real issue may be that the plugin should allow you to specify the path of the SVN workspace (with the default being the project root dir), but I will give my requirements (specifically the need to use an SVN workspace checked-out in a sub-folder of the project) some more thought before taking this issue further.  Happy for the issue to be closed until then. 

Thanks.

**Comment by neiljbrown** [comment]
I will give my requirements (specifically the need to use an SVN workspace checked-out in a sub-folder of the project) some more thought before taking this issue further. Happy for the issue to be closed until then.

**Comment by martoe** [comment]
Documentation improved, thanks for the input!
