### ISSUE TITLE
Add support for svn checkout

### ISSUE THREAD

**Issue by neiljbrown** [martoe/gradle-svntools-plugin#8]
Hi Martin, 

Do you have any plans to enhance the plugin to support for additional svn commands? I’d suggest that adding svn checkout would increase the usefulness and hence take-up of the plugin. (I certainly need it to automate a release process in my build script). For now I’m having to use svnant instead.

Thanks.

**Comment by martoe** [comment]
Sounds like a chicken-egg-dilemma to me: all my Gradle scripts are stored in SCM, so I have to do an SCM checkout *before* running Gradle. Therefore I had no need for a "checkout" task yet.
Can you describe your usecase?

**Comment by neiljbrown** [comment]
Hi Martin, 

The release process for my services, which is automated in a custom gradle 'release' task, includes checking out the (version) tag for the new release.  A developer will have previously manually checked-out the project, including build.gradle, but they will subsequently use gradle to perform the release.

Neil.

**Comment by martoe** [comment]
Hi Neil,
I have implemented a simple checkout task in the "develop" branch. Do you need additional configuration options?
Cheers, Martin

**Comment by neiljbrown** [comment]
Hi Martin, I will take a look at the changes as soon as I can, and get back to you. Many thanks for working on the enhancement. Neil.

**Comment by neiljbrown** [comment]
Hi Martin, I trialled the first commit de744d3 which mostly looked fine and met my needs. I did have a few observations, however I can see you've addressed some of those (e.g. the type of the targetDir property and validating it is supplied). Let me take another look at the latest updates.

**Comment by martoe** [comment]
Plugin v1.1 released, thanks for your input Neil!

**Comment by neiljbrown** [comment]
Great! You're welcome. Thank-you for the updates.
