### ISSUE TITLE
Enhance SvnTag task to support copying from repo URL

### ISSUE THREAD

**Issue by neiljbrown** [martoe/gradle-svntools-plugin#9]
Hi Martin, 

Do you have any plans to enhance the SvnTag task to support the more common practice of creating a tag by copying the trunk folder from the remote repo, using a specified URL, rather than copying from the  local workspace?

Thanks.

**Comment by martoe** [comment]
Sounds good. I will see that I find some time for this...

**Comment by neiljbrown** [comment]
Hi, just to let you know I no longer have an immediate need for this enhancement any longer, so it can either be treated as low priority and moved to the backlog, or closed. Thanks.
